package com.ERP.model;

// Generated Dec 6, 2014 6:06:15 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ItemListId generated by hbm2java
 */
@Embeddable
public class ItemListId implements java.io.Serializable {

	@Column(name = "ITEM_COUNT", nullable = false)
	private long itemCount;

	@Column(name = "ITEM_ID", nullable = false)
	private long itemId;

	public ItemListId() {
	}

	public ItemListId(long itemCount, long itemId) {
		this.itemCount = itemCount;
		this.itemId = itemId;
	}

	public long getItemCount() {
		return this.itemCount;
	}

	public void setItemCount(long itemCount) {
		this.itemCount = itemCount;
	}

	public long getItemId() {
		return this.itemId;
	}

	public void setItemId(long itemId) {
		this.itemId = itemId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ItemListId))
			return false;
		ItemListId castOther = (ItemListId) other;

		return (this.getItemCount() == castOther.getItemCount())
				&& (this.getItemId() == castOther.getItemId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getItemCount();
		result = 37 * result + (int) this.getItemId();
		return result;
	}

}
