<%-- 
    Document   : challan_add
    Created on : 7 Feb, 2015, 7:46:25 PM
    Author     : shweta
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@page contentType="text/html" import="java.io.*,java.util.*"%>
<%@page import="java.text.SimpleDateFormat" %>  
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="CSS/normalize.css" rel="stylesheet" type="text/css">
        <script src="JS/modernizr.js" type="text/javascript"></script>
        <script src="JS/jquery-2.1.3.min.js" type="text/javascript"></script>
		<!-- <script type="text/javascript" src="http://www.technicalkeeda.com/js/javascripts/plugin/jquery.js"></script> 
		<script type="text/javascript" src="http://www.technicalkeeda.com/js/javascripts/plugin/json2.js"></script> -->
        <script src="JS/validate_challan.js" type="text/javascript"></script>
        <link href="CSS/style1.css" rel="stylesheet" type="text/css">
        <link href="CSS/columns.css" rel="stylesheet" type="text/css">
        <link href="CSS/tablestyle.css" rel="stylesheet" type="text/css">
        <title>ADD CHALLAN</title>
    </head>
    <body>
        <div class="title">
            <span>ADD CHALLAN</span>
        </div>
        <div class="content clearfix">
            <form id="frm_add_challan1">
                <div class="small_content">
                    <label for="ddlprojname">Project Name</label>
                     <select name="ddlprojname" id="ddlprojname">
                       		<c:forEach items="${projectName}" var="projectName">
								<option value="${projectName}">${projectName}</option>
							</c:forEach>
                     </select> 
                    <input type="button" value="SEARCH" id="btn_search" name="btn_frm_add_challan1"/>
                    <p id="p_msg"><label id="lbl_msgbox"></label></p>
                </div>
                <table id="tbl_challan">
                   <!--  <thead>
                        <tr>                         
                            <th>PO No.</th>
                            <th>Item</th>
                            <th>Delivery Site</th>
                        </tr>
                    </thead>
                    <tr>                           
                        <td><input type="checkbox" name="chkpo" id="c1"/>c1</td>
                        <td>DYNAMIC TABLE</td>
                        <td>DYNAMIC TABLE</td>
                    </tr>
                    <tr>                           
                        <td><input type="checkbox" name="chkpo" id="c2"/>c2</td>
                        <td>DYNAMIC TABLE</td>
                        <td>DYNAMIC TABLE</td>
                    </tr>
                    <tr>                           
                        <td><input type="checkbox" name="chkpo" id="c3"/>c3</td>
                        <td>DYNAMIC TABLE</td>
                        <td>DYNAMIC TABLE</td>
                    </tr> -->
                </table>
            </form>
            <br>
            <%Date dNow = new Date();
                SimpleDateFormat full_date = new SimpleDateFormat("dd-MM-yyyy");
                java.util.Date today_date = new java.util.Date();
                String display_date = full_date.format(today_date);
            %>
            <form id="frm_add_challan2" class="rrc_frm">
                <h2><u>Challan Details</u></h2>
                <div class="content_column">
                    <label for="txtchallnolabel">Challan No.</label> 
                    <input type="text" id="txtchallno"  placeholder="autogenerated" />
                    <label for="txtponolabel">Purchase Order No.</label> 
                    <input type="text" id="txtpono" placeholder="autogenerated" />
                    <label for="txtrdatelabel">Date of Receipt</label> 
                    <input type="text" id="txtrdate" placeholder="Current date"  value="<%=display_date%>"/>
                </div>

                <div class="content_column">
                    <label id="spandeladdress" for="tadeladdresslabel">Delivery Address</label> 
                    <textarea id="tadeladdress"></textarea>  
                    <label for="txtupstreamlabel">Upstream details</label> 
                    <input type="text" id="txtupstream" placeholder="suggest vendor name" />
                    <label id="spantc" for="tatclabel">Term & Conditions</label>
                    <textarea id="tatc" placeholder="will be provided ">
                    </textarea>
                </div>
                <table id="tbl_addch" class="clearfix">
                    <thead>
                        <tr>                         
                            <th>Serial No.</th>
                            <th>Item</th>
                            <th>Grade</th>
                            <th>Quantity</th>
                            <th>Unit</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>                           
                            <td><input type="text" id="td_serial" value="1" placeholder="autogenerated" /></td>
                            <td><input type="text" id="td_item" placeholder="autogenerated" /></td>
                            <td><input type="text" id="td_grade" placeholder="autogenerated" /></td>
                            <td><input type="text" id="td_qty" placeholder="autogenerated" /></td>
                            <td><input type="text" id="td_unit" placeholder="autogenerated" /></td>
                        </tr>
                    </tbody>
                </table>
                <div class="submit_wrap">
                    <p id="p_chmsg"><label id="lbl_msgbox"></label></p>
                    <input type="submit" value="GENERATE" id="btn_challan_add2" class="submit_btn">
                </div>
            </form>
        </div>

    </body>
</html>
