package com.jerrymouse.entity;

// Generated Dec 6, 2014 6:06:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * EmpDetails generated by hbm2java
 */
@Entity
@Table(name = "emp_details", catalog = "procurement")
public class EmpDetails implements java.io.Serializable {

	private String userNm;
	private EmpLogin empLogin;
	private String empAddr;
	private String empEmail;
	private String empRole;
	private String empTel1;
	private String empTel2;
	private String firstNm;
	private String lastNm;
	private String midNm;
	private String empProj;
	private Set<EmployeeProjectJoin> employeeProjectJoins = new HashSet<EmployeeProjectJoin>(
			0);

	public EmpDetails() {
	}

	public EmpDetails(EmpLogin empLogin) {
		this.empLogin = empLogin;
	}

	public EmpDetails(EmpLogin empLogin, String empAddr, String empEmail,
			String empRole, String empTel1, String empTel2, String firstNm,
			String lastNm, String midNm, String empProj,
			Set<EmployeeProjectJoin> employeeProjectJoins) {
		this.empLogin = empLogin;
		this.empAddr = empAddr;
		this.empEmail = empEmail;
		this.empRole = empRole;
		this.empTel1 = empTel1;
		this.empTel2 = empTel2;
		this.firstNm = firstNm;
		this.lastNm = lastNm;
		this.midNm = midNm;
		this.empProj = empProj;
		this.employeeProjectJoins = employeeProjectJoins;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "empLogin"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "user_nm", unique = true, nullable = false)
	public String getUserNm() {
		return this.userNm;
	}

	public void setUserNm(String userNm) {
		this.userNm = userNm;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	@JsonBackReference
	public EmpLogin getEmpLogin() {
		return this.empLogin;
	}

	public void setEmpLogin(EmpLogin empLogin) {
		this.empLogin = empLogin;
	}

	@Column(name = "emp_addr")
	public String getEmpAddr() {
		return this.empAddr;
	}

	public void setEmpAddr(String empAddr) {
		this.empAddr = empAddr;
	}

	@Column(name = "emp_email")
	public String getEmpEmail() {
		return this.empEmail;
	}

	public void setEmpEmail(String empEmail) {
		this.empEmail = empEmail;
	}

	@Column(name = "emp_role")
	public String getEmpRole() {
		return this.empRole;
	}

	public void setEmpRole(String empRole) {
		this.empRole = empRole;
	}

	@Column(name = "emp_tel1")
	public String getEmpTel1() {
		return this.empTel1;
	}

	public void setEmpTel1(String empTel1) {
		this.empTel1 = empTel1;
	}

	@Column(name = "emp_tel2")
	public String getEmpTel2() {
		return this.empTel2;
	}

	public void setEmpTel2(String empTel2) {
		this.empTel2 = empTel2;
	}

	@Column(name = "first_nm")
	public String getFirstNm() {
		return this.firstNm;
	}

	public void setFirstNm(String firstNm) {
		this.firstNm = firstNm;
	}

	@Column(name = "last_nm")
	public String getLastNm() {
		return this.lastNm;
	}

	public void setLastNm(String lastNm) {
		this.lastNm = lastNm;
	}

	@Column(name = "mid_nm")
	public String getMidNm() {
		return this.midNm;
	}

	public void setMidNm(String midNm) {
		this.midNm = midNm;
	}

	@Column(name = "emp_proj")
	public String getEmpProj() {
		return this.empProj;
	}

	public void setEmpProj(String empProj) {
		this.empProj = empProj;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empDetails", cascade = CascadeType.ALL)
	public Set<EmployeeProjectJoin> getEmployeeProjectJoins() {
		return this.employeeProjectJoins;
	}

	public void setEmployeeProjectJoins(
			Set<EmployeeProjectJoin> employeeProjectJoins) {
		this.employeeProjectJoins = employeeProjectJoins;
	}

}
