package com.jerrymouse.entity;

// Generated Dec 6, 2014 6:06:15 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonManagedReference;

/**
 * EmpLogin generated by hbm2java
 */
@Entity
@Table(name = "emp_login", catalog = "procurement")
public class EmpLogin implements java.io.Serializable {

	private String userNm;
	private String password;
	private EmpDetails empDetails;

	public EmpLogin() {
	}

	public EmpLogin(String userNm) {
		this.userNm = userNm;
	}

	public EmpLogin(String userNm, String password, EmpDetails empDetails) {
		this.userNm = userNm;
		this.password = password;
		this.empDetails = empDetails;
	}

	@Id
	@Column(name = "user_nm", unique = true, nullable = false)
	public String getUserNm() {
		return this.userNm;
	}

	public void setUserNm(String userNm) {
		this.userNm = userNm;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "empLogin", cascade = CascadeType.ALL)
	@JsonManagedReference
	public EmpDetails getEmpDetails() {
		return this.empDetails;
	}

	public void setEmpDetails(EmpDetails empDetails) {
		this.empDetails = empDetails;
	}

}
