package com.jerrymouse.entity;

// Generated Dec 6, 2014 6:06:15 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ItemList generated by hbm2java
 */
@Entity
@Table(name = "item_list", catalog = "procurement")
public class ItemList implements java.io.Serializable {

	private ItemListId id;
	private MatRequi matRequi;
	private String item;
	private String itemGrd;
	private Double itemQty;
	private String unit;
	private String usedFor;

	public ItemList() {
	}

	public ItemList(ItemListId id, MatRequi matRequi) {
		this.id = id;
		this.matRequi = matRequi;
	}

	public ItemList(ItemListId id, MatRequi matRequi, String item,
			String itemGrd, Double itemQty, String unit) {
		this.id = id;
		this.matRequi = matRequi;
		this.item = item;
		this.itemGrd = itemGrd;
		this.itemQty = itemQty;
		this.unit = unit;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "itemCount", column = @Column(name = "item_count", nullable = false)),
			@AttributeOverride(name = "itemId", column = @Column(name = "item_id", nullable = false)) })
	public ItemListId getId() {
		return this.id;
	}

	public void setId(ItemListId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "item_id", referencedColumnName = "req_no", nullable = false, insertable = false, updatable = false)
	public MatRequi getMatRequi() {
		return this.matRequi;
	}

	public void setMatRequi(MatRequi matRequi) {
		this.matRequi = matRequi;
	}

	@Column(name = "item")
	public String getItem() {
		return this.item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	@Column(name = "item_grd")
	public String getItemGrd() {
		return this.itemGrd;
	}

	public void setItemGrd(String itemGrd) {
		this.itemGrd = itemGrd;
	}

	@Column(name = "item_qty", precision = 22, scale = 0)
	public Double getItemQty() {
		return this.itemQty;
	}

	public void setItemQty(Double itemQty) {
		this.itemQty = itemQty;
	}

	@Column(name = "unit")
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "used_for")
	public String getUsedFor() {
		return this.usedFor;
	}

	public void setUsedFor(String usedFor) {
		this.usedFor = usedFor;
	}

}
