package com.jerrymouse.entity;

// Generated Dec 6, 2014 6:06:15 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project", catalog = "procurement")
public class Project implements java.io.Serializable {

	private Integer projectId;
	private String projSect;
	private String projNm;
	private String delAddr;
	private Set<MatRequi> matRequis = new HashSet<MatRequi>(0);
	private Set<EmployeeProjectJoin> employeeProjectJoins = new HashSet<EmployeeProjectJoin>(
			0);

	// private Set<PurOrder> purOrders = new HashSet<PurOrder>(0);

	public Project() {
	}

	public Project(String projSect) {
		this.projSect = projSect;
	}

	public Project(String projSect, String projNm, Set<MatRequi> matRequis,
			Set<EmployeeProjectJoin> employeeProjectJoins/*
														 * , Set<PurOrder>
														 * purOrders
														 */) {
		this.projSect = projSect;
		this.projNm = projNm;
		this.matRequis = matRequis;
		this.employeeProjectJoins = employeeProjectJoins;
		// this.purOrders = purOrders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "project_id", unique = true, nullable = false)
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "proj_sect", nullable = false)
	public String getProjSect() {
		return this.projSect;
	}

	public void setProjSect(String projSect) {
		this.projSect = projSect;
	}

	@Column(name = "proj_nm")
	public String getProjNm() {
		return this.projNm;
	}

	public void setProjNm(String projNm) {
		this.projNm = projNm;
	}

	@Column(name = "del_addr")
	public String getDelAddr() {
		return delAddr;
	}

	public void setDelAddr(String delAddr) {
		this.delAddr = delAddr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project", cascade = CascadeType.ALL)
	public Set<MatRequi> getMatRequis() {
		return this.matRequis;
	}

	public void setMatRequis(Set<MatRequi> matRequis) {
		this.matRequis = matRequis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project", cascade = CascadeType.ALL)
	public Set<EmployeeProjectJoin> getEmployeeProjectJoins() {
		return this.employeeProjectJoins;
	}

	public void setEmployeeProjectJoins(
			Set<EmployeeProjectJoin> employeeProjectJoins) {
		this.employeeProjectJoins = employeeProjectJoins;
	}

	/*
	 * @OneToMany(fetch = FetchType.LAZY, mappedBy = "project", cascade =
	 * CascadeType.ALL) public Set<PurOrder> getPurOrders() { return
	 * this.purOrders; }
	 * 
	 * public void setPurOrders(Set<PurOrder> purOrders) { this.purOrders =
	 * purOrders; }
	 */

}
