package com.jerrymouse.entity;

// Generated Dec 6, 2014 6:06:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurOrder generated by hbm2java
 */
@Entity
@Table(name = "pur_order", catalog = "procurement")
public class PurOrder implements java.io.Serializable {

	private Long poNo;
	// private Project project;
	private Date detDt;
	private Date poDt;
	private String purGrd;
	private String purItem;
	private Double purQty;
	private Double purRate;
	private String supNm;
	private Set<RequiPur> requiPurs = new HashSet<RequiPur>(0);
	private Set<ChallanDetails> challanDetailses = new HashSet<ChallanDetails>(
			0);

	public PurOrder() {
	}

	public PurOrder(/* Project project, */Date detDt, Date poDt, String purGrd,
			String purItem, Double purQty, Double purRate, String supNm,
			Set<RequiPur> requiPurs, Set<ChallanDetails> challanDetailses) {
		// this.project = project;
		this.detDt = detDt;
		this.poDt = poDt;
		this.purGrd = purGrd;
		this.purItem = purItem;
		this.purQty = purQty;
		this.purRate = purRate;
		this.supNm = supNm;
		this.requiPurs = requiPurs;
		this.challanDetailses = challanDetailses;
	}

	@Id
	/* @GeneratedValue(strategy = IDENTITY) */
	@Column(name = "po_no", unique = true, nullable = false)
	public Long getPoNo() {
		return this.poNo;
	}

	public void setPoNo(Long poNo) {
		this.poNo = poNo;
	}

	/*
	 * @ManyToOne(fetch = FetchType.LAZY)
	 * 
	 * @JoinColumn(name = "del_addr") public Project getProject() { return
	 * this.project; }
	 * 
	 * public void setProject(Project project) { this.project = project; }
	 */

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "det_dt", length = 19)
	public Date getDetDt() {
		return this.detDt;
	}

	public void setDetDt(Date detDt) {
		this.detDt = detDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "po_dt", length = 19)
	public Date getPoDt() {
		return this.poDt;
	}

	public void setPoDt(Date poDt) {
		this.poDt = poDt;
	}

	@Column(name = "pur_grd")
	public String getPurGrd() {
		return this.purGrd;
	}

	public void setPurGrd(String purGrd) {
		this.purGrd = purGrd;
	}

	@Column(name = "pur_item")
	public String getPurItem() {
		return this.purItem;
	}

	public void setPurItem(String purItem) {
		this.purItem = purItem;
	}

	@Column(name = "pur_qty", precision = 22, scale = 0)
	public Double getPurQty() {
		return this.purQty;
	}

	public void setPurQty(Double purQty) {
		this.purQty = purQty;
	}

	@Column(name = "pur_rate", precision = 22, scale = 0)
	public Double getPurRate() {
		return this.purRate;
	}

	public void setPurRate(Double purRate) {
		this.purRate = purRate;
	}

	@Column(name = "sup_nm")
	public String getSupNm() {
		return this.supNm;
	}

	public void setSupNm(String supNm) {
		this.supNm = supNm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "purOrder", cascade = CascadeType.ALL)
	public Set<RequiPur> getRequiPurs() {
		return this.requiPurs;
	}

	public void setRequiPurs(Set<RequiPur> requiPurs) {
		this.requiPurs = requiPurs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "purOrder", cascade = CascadeType.ALL)
	public Set<ChallanDetails> getChallanDetailses() {
		return this.challanDetailses;
	}

	public void setChallanDetailses(Set<ChallanDetails> challanDetailses) {
		this.challanDetailses = challanDetailses;
	}

}
