package com.jerrymouse.entity;

// Generated Dec 6, 2014 6:06:15 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RequiPur generated by hbm2java
 */
@Entity
@Table(name = "requi_pur", catalog = "procurement")
public class RequiPur implements java.io.Serializable {

	private Integer id;
	private MatRequi matRequi;
	private PurOrder purOrder;

	public RequiPur() {
	}

	public RequiPur(MatRequi matRequi, PurOrder purOrder) {
		this.matRequi = matRequi;
		this.purOrder = purOrder;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "req_no", nullable = false)
	public MatRequi getMatRequi() {
		return this.matRequi;
	}

	public void setMatRequi(MatRequi matRequi) {
		this.matRequi = matRequi;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "po_no", nullable = false)
	public PurOrder getPurOrder() {
		return this.purOrder;
	}

	public void setPurOrder(PurOrder purOrder) {
		this.purOrder = purOrder;
	}

}
